+ cd simulations
+ PROGRAM=maximal_matching
+ GRAPH=graph_7
+ NO_SIMS=10000
+ FAULT_INTERVAL=2
+ LIMIT_STEPS=100
+ SIMULATION_TYPE=controlled_at_node_amit_v1
+ python simulate.py --program maximal_matching --sched 0 --no-sim 10000 --fault-interval 2 --graph-names graph_7 --fault-prob 1.0 --simulation-type controlled_at_node_amit_v1 --controlled-at-node 0 --limit-steps 100
Locating Graph: "graph_7".
Analysis graph: graph_7 | program: maximal_matching | Simulation Type: controlled_at_node_amit_v1, Args: [0] | No. of Simulations: 10000 | Scheduler: 0 | Mutual Exclusion: False | Fault Interval: 2
Total configs: 11,796,480.
Simulation environment: No. of Simulations: 10000 | Scheduler: CENTRAL | ME: False

Saving result at results/maximal_matching/graph_7__0__controlled_at_node_amit_v1_args_0__10000__False__2__limits_100.csv
+ python simulate.py --program maximal_matching --sched 0 --no-sim 10000 --fault-interval 2 --graph-names graph_7 --fault-prob 1.0 --simulation-type controlled_at_node_amit_v1 --controlled-at-node 4 --limit-steps 100
Locating Graph: "graph_7".
Analysis graph: graph_7 | program: maximal_matching | Simulation Type: controlled_at_node_amit_v1, Args: [4] | No. of Simulations: 10000 | Scheduler: 0 | Mutual Exclusion: False | Fault Interval: 2
Total configs: 11,796,480.
Simulation environment: No. of Simulations: 10000 | Scheduler: CENTRAL | ME: False

Saving result at results/maximal_matching/graph_7__0__controlled_at_node_amit_v1_args_4__10000__False__2__limits_100.csv
+ python simulate.py --program maximal_matching --sched 0 --no-sim 10000 --fault-interval 2 --graph-names graph_7 --fault-prob 1.0 --simulation-type controlled_at_node_amit_v1 --controlled-at-node 9 --limit-steps 100
Locating Graph: "graph_7".
Analysis graph: graph_7 | program: maximal_matching | Simulation Type: controlled_at_node_amit_v1, Args: [9] | No. of Simulations: 10000 | Scheduler: 0 | Mutual Exclusion: False | Fault Interval: 2
Total configs: 11,796,480.
Simulation environment: No. of Simulations: 10000 | Scheduler: CENTRAL | ME: False

Saving result at results/maximal_matching/graph_7__0__controlled_at_node_amit_v1_args_9__10000__False__2__limits_100.csv
+ SIMULATION_TYPE=controlled_at_node_amit_v2
+ python simulate.py --program maximal_matching --sched 0 --no-sim 10000 --fault-interval 2 --graph-names graph_7 --fault-prob 1.0 --simulation-type controlled_at_node_amit_v2 --controlled-at-node 0 --limit-steps 100
Locating Graph: "graph_7".
Analysis graph: graph_7 | program: maximal_matching | Simulation Type: controlled_at_node_amit_v2, Args: [] | No. of Simulations: 10000 | Scheduler: 0 | Mutual Exclusion: False | Fault Interval: 2
Total configs: 11,796,480.
Simulation environment: No. of Simulations: 10000 | Scheduler: CENTRAL | ME: False
Traceback (most recent call last):
  File "/home/agaru/research/cvf-python-gnn/simulations/simulate.py", line 170, in <module>
    main(
    ~~~~^
        graph_name,
        ^^^^^^^^^^^
    ...<9 lines>...
        simulation_type_args,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/agaru/research/cvf-python-gnn/simulations/simulate.py", line 90, in main
    result = simulation.start_simulation(*simulation_type_args)
  File "/home/agaru/research/cvf-python-gnn/simulations/simulation.py", line 416, in start_simulation
    inner_results = self.run_simulations(state, *simulation_type_args)
  File "/home/agaru/research/cvf-python-gnn/simulations/simulation.py", line 370, in run_simulations
    faulty_actions = faulty_action_generator(state, *extra_args, step)
  File "/home/agaru/research/cvf-python-gnn/simulations/simulation.py", line 347, in get_faulty_actions_controlled_at_node_v2
    faulty_actions = self.inject_fault_at_node_v2(state, process)
  File "/home/agaru/research/cvf-python-gnn/simulations/simulation.py", line 214, in inject_fault_at_node_v2
    p[process] = 1.0
    ~^^^^^^^^^
IndexError: list assignment index out of range
